# Site settings
title: Minki's Portfolio | Industrial AI Engineer
email: kenya7938@gmail.com
description: > 
  Industrial AI & Machine Vision Developer Portfolio
baseurl: "" 
url: "https://minki9252.github.io" 

# Social accounts
github_username: minki9252
# twitter_username 항목은 사용하지 않는다면 비워두셔도 됩니다.
